"""Read models for the console.

Every endpoint here is a projection over state that already exists: the cases
table, the append-only ledger, and the two generated evidence files. Nothing is
computed for display only.

Two rules hold across this module, and both exist because the alternative is a
page that quietly disagrees with the system behind it.

1. **No measured number is written here.** The evaluation results are read from
   `docs/evidence/evaluation.json`, which `make eval` regenerates from the same
   run that writes `EVALUATION.md`. A percentage typed into a template is a
   percentage that can drift from the harness, and no test would catch it.

2. **Simulated and real are never mixed silently.** Cases generated for the
   benchmark and the one case that went through real Razorpay are both shown,
   and every payload says which it is.
"""

from __future__ import annotations

import json
from datetime import UTC, datetime, timedelta
from functools import lru_cache

from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy import func, select, text
from sqlalchemy.orm import Session

from app.allocator.budget import IST, BudgetPolicy
from app.config import REPO_ROOT
from app.db import get_db
from app.models import Action, ActionStatus, Case, CaseEvent, CaseStatus

router = APIRouter(prefix="/api", tags=["console"])

EVIDENCE = REPO_ROOT / "docs" / "evidence"

#: Ledger event emitted when a stopping rule refuses a case before planning.
STOPPED = "case.stopped"

#: Ledger event emitted when the allocator plans and then declines to act.
SUPPRESSED = "case.suppressed"


def _read_evidence(name: str) -> dict:
    path = EVIDENCE / name
    if not path.exists():
        raise HTTPException(
            status.HTTP_503_SERVICE_UNAVAILABLE,
            f"{name} has not been generated; run `make eval`",
        )
    return json.loads(path.read_text())


@lru_cache(maxsize=4)
def _cached_evidence(name: str, mtime: float) -> dict:
    """Evidence files are regenerated by a build step, not by the request path.

    Keyed on mtime so a regenerated file is picked up without a restart, and so
    a stale read is impossible rather than merely unlikely.
    """
    return _read_evidence(name)


def _evidence(name: str) -> dict:
    path = EVIDENCE / name
    mtime = path.stat().st_mtime if path.exists() else 0.0
    return _cached_evidence(name, mtime)


@router.get("/facts")
def facts() -> dict:
    """The measured evaluation results, exactly as `make eval` produced them."""
    return _evidence("evaluation.json")


@router.get("/evidence")
def evidence() -> dict:
    """The one case that went through real Razorpay, start to finish."""
    return {"real": True, **_evidence("real_loop.json")}


@router.get("/overview")
def overview(db: Session = Depends(get_db)) -> dict:
    """Live counts over the cases table.

    `at_risk` deliberately excludes recovered cases. Money that came back is not
    money at risk, and a headline that conflates them only ever moves up.
    """
    by_status = {
        row.status.value: row.n
        for row in db.execute(
            select(Case.status, func.count().label("n")).group_by(Case.status)
        ).all()
    }

    def _sum(*statuses: CaseStatus) -> int:
        # int() is not cosmetic. psycopg returns SUM over a BIGINT as Decimal,
        # and FastAPI serialises Decimal as a JSON *string* -- so the amounts
        # arrived in the browser as "2385375.3" and every arithmetic operation
        # on them silently became string concatenation.
        total = db.scalar(
            select(func.coalesce(func.sum(Case.amount_paise), 0)).where(Case.status.in_(statuses))
        )
        return int(total or 0)

    open_statuses = [s for s in CaseStatus if s is not CaseStatus.RECOVERED]
    recovered_paise = _sum(CaseStatus.RECOVERED)

    # Count the actions, not the cases. A case whose action is awaiting a human
    # keeps status DIAGNOSED -- the queue is a property of the action -- so
    # counting cases by status reported an empty queue while three sat in it.
    awaiting = (
        db.scalar(
            select(func.count())
            .select_from(Action)
            .where(Action.status == ActionStatus.PENDING_APPROVAL)
        )
        or 0
    )

    now = datetime.now(UTC)
    window = now - timedelta(hours=24)
    contacts_today = (
        db.scalar(
            select(func.count())
            .select_from(Action)
            .where(Action.status == ActionStatus.EXECUTED)
            .where(Action.executed_at >= window)
        )
        or 0
    )

    deferred = (
        db.scalar(
            select(func.count())
            .select_from(Action)
            .where(Action.status == ActionStatus.PROPOSED)
            .where(Action.scheduled_for.is_not(None))
        )
        or 0
    )

    policy = BudgetPolicy()
    return {
        "cases_total": sum(by_status.values()),
        "by_status": by_status,
        "at_risk_rupees": _sum(*open_statuses) / 100,
        "recovered_rupees": recovered_paise / 100,
        "recovered_cases": by_status.get(CaseStatus.RECOVERED.value, 0),
        "awaiting_approval": awaiting,
        "contacts_last_24h": contacts_today,
        "scheduled": deferred,
        "quiet_hours": {
            "start_ist": policy.quiet_hours_start,
            "end_ist": policy.quiet_hours_end,
            "now_ist": now.astimezone(IST).strftime("%H:%M"),
            "active": policy.is_quiet_at(now),
        },
    }


@router.get("/queue")
def queue(limit: int = 25, db: Session = Depends(get_db)) -> list[dict]:
    """Actions a human has to decide on, most valuable first.

    Ordered by amount rather than arrival: a reviewer who works the queue top
    down should be working the money, and the queue is the one place where the
    ordering is a person's attention rather than a contact budget.
    """
    rows = db.execute(
        select(Action, Case)
        .join(Case, Case.id == Action.case_id)
        .where(Action.status == ActionStatus.PENDING_APPROVAL)
        .order_by(Case.amount_paise.desc())
        .limit(limit)
    ).all()
    return [
        {
            "action_id": action.id,
            "case_id": case.id,
            "external_ref": case.external_ref,
            "channel": case.channel.value,
            "action_type": action.action_type,
            "amount_rupees": case.amount_paise / 100,
            "cause": case.cause,
            "cause_confidence": case.cause_confidence,
            "cause_method": case.cause_method.value if case.cause_method else None,
            "why_queued": action.approval_reason,
            "predicted_uplift": action.predicted_recovery_prob,
            "expected_value_rupees": (
                action.expected_value_paise / 100
                if action.expected_value_paise is not None
                else None
            ),
            "decided_by_rule": action.decided_by_rule,
            "error_reason": case.error_reason,
            "error_source": case.error_source,
        }
        for action, case in rows
    ]


@router.get("/rules")
def rules(db: Session = Depends(get_db)) -> list[dict]:
    """Every action the system did not simply carry out, and why.

    This is the panel the rest of the console exists to make visible. Other
    panels show work the system did; this one shows work it declined, altered or
    postponed, which is the harder thing for an automated system to be trusted
    about.

    Three outcomes are reported, and they are **not** the same thing. Collapsing
    them into one "blocked" count would be the easy read and the wrong one:

    - ``stopped``    the case was never planned. A stopping rule refused it
                     before the allocator was consulted.
    - ``suppressed`` the allocator planned and then declined -- the economics
                     did not clear the floor, or a risk guardrail forbade contact.
    - ``deferred``   the action was approved and its send time moved. Quiet
                     hours postpone a contact; they never cancel one, and
                     counting them as blocked would overstate this panel.
    """
    out: list[dict] = []

    for event_type, outcome in ((STOPPED, "stopped"), (SUPPRESSED, "suppressed")):
        rows = db.execute(
            select(
                CaseEvent.payload["rule"].astext.label("rule"),
                func.count().label("n"),
            )
            .where(CaseEvent.event_type == event_type)
            # Grouped by the output alias. Restating the JSONB expression makes
            # SQLAlchemy emit a second bind parameter, and Postgres then rejects
            # the two occurrences as different expressions.
            .group_by(text("rule"))
        ).all()
        out += [{"rule": row.rule, "count": row.n, "outcome": outcome} for row in rows if row.rule]

    deferred = db.execute(
        select(Action.decided_by_rule, func.count().label("n"))
        .where(Action.decided_by_rule.is_not(None))
        .where(Action.decided_by_rule == "quiet_hours")
        .group_by(Action.decided_by_rule)
    ).all()
    out += [
        {"rule": row.decided_by_rule, "count": row.n, "outcome": "deferred"} for row in deferred
    ]

    return sorted(out, key=lambda r: -r["count"])


@router.get("/scheduled")
def scheduled(limit: int = 12, db: Session = Depends(get_db)) -> list[dict]:
    """Contacts that are decided but deliberately not sent yet.

    Two rules put an action here, and both are things the system knows that a
    blind retry loop does not: the cause implies a better moment (48 hours after
    an insufficient-funds failure lands after payday), or the moment it implies
    falls inside quiet hours.

    Both used to be computed and then ignored -- the executor sent every contact
    immediately while the ledger recorded the deferral that had not happened.
    """
    now = datetime.now(UTC)
    rows = db.execute(
        select(Action, Case)
        .join(Case, Case.id == Action.case_id)
        .where(Action.status == ActionStatus.PROPOSED)
        .where(Action.scheduled_for.is_not(None))
        .order_by(Action.scheduled_for)
        .limit(limit)
    ).all()
    return [
        {
            "action_id": action.id,
            "external_ref": case.external_ref,
            "action_type": action.action_type,
            "cause": case.cause,
            "amount_rupees": case.amount_paise / 100,
            "due_at": action.scheduled_for.isoformat(),
            "due_in_hours": round((action.scheduled_for - now).total_seconds() / 3600.0, 1),
            "rule": action.decided_by_rule,
        }
        for action, case in rows
    ]


@router.get("/ledger")
def ledger(limit: int = 40, db: Session = Depends(get_db)) -> list[dict]:
    """The newest ledger entries across every case.

    Append-only, so "newest" is unambiguous and nothing shown here can later
    turn out to have said something else.
    """
    rows = db.execute(
        select(CaseEvent, Case)
        .join(Case, Case.id == CaseEvent.case_id)
        .order_by(CaseEvent.id.desc())
        .limit(limit)
    ).all()
    return [
        {
            "seq": event.seq,
            "case_id": event.case_id,
            "external_ref": case.external_ref,
            "event": event.event_type,
            "actor": event.actor,
            "at": event.created_at.isoformat(),
            "amount_rupees": case.amount_paise / 100,
            "payload": event.payload,
        }
        for event, case in rows
    ]
